version: ""

formatter: markdown table

name: terraform-module-state-s3-bucket

content: |-

  # terraform-module-state-s3-bucket
  
  ## s3-bucket-tfstate.tf example:

  Create an s3-bucket-tfstate.tf file in the Terraform root directory with the following configuration:

  ```hcl
  ################################################################################
  # Terraform Remote State Amazon S3 Bucket
  ################################################################################

  module "terraform_state" {
    source        = "git::https://github.com/fapd777/terraform-module-state-s3-bucket.git"
    name_prefix   = var.name_prefix
    name_suffix   = var.region
    log_bucket_id = var.logging_bucket
  }
  ```
  
  ## state.tf example:

  Create an state.tf file in the Terraform root directory with the following configuration:

  ```hcl
  terraform {
    backend "s3" {
      acl     = "bucket-owner-full-control"
      encrypt = true
      region  = "us-east-2"
    }
  }
  ```

  ## init-tfvars/dev.tfvars example:

  Create an dev.tfvars file in the Terraform init-tfvars directory with the following configuration:

  ```hcl
  # These variables are called when running the following command:
  # terraform init -backend-config=./init-tfvars/dev.tfvars
  bucket         = "aws-s3-service-remote-state-backend-us-east-2"
  key            = "aws-s3-service-dev-remote-state-backend.tfstate"
  dynamodb_table = "aws-s3-service-remote-state-backend-us-east-2"
  kms_key_id     = "arn:aws:kms:us-east-2:1234567890AB:key/12345678-90AB-CDEF-GHIJ-KLMNOPQRSTYWXYZ"
  ```

  
  ## How to initialize the backend:
  ```
  terraform init -backend-config=./init-tfvars/dev.tfvars
  ```

  ---

  {{ .Resources }}

  {{ .Inputs }}

  {{ .Outputs }}

  ---

  <span style="color:red">Note:</span> Manual changes to the README will be overwritten when the documentation is updated. To update the documentation, run `terraform-docs -c .config/.terraform-docs.yml .`

sections:
  show:
    - resources
    - inputs
    - outputs
    - providers
    - requirements

sort:
  enabled: true
  by: name

settings:
  color: true

output:
  file: README.md
  mode: replace
